language: julia
julia:
  - release
  - nightly
notifications:
    email: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("$name")'
  - if [ -f test/runtests.jl ]; then julia --check-bounds=yes --code-coverage test/runtests.jl; fi
after_success:
  - julia -e 'cd(Pkg.dir("JuliaFem")); Pkg.add("Coverage"); using Coverage; >Coveralls.submit(Coveralls.process_folder())'
