language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("JuliaFEM"); Pkg.test("JuliaFEM"; coverage=true)'
  - julia -e 'Pkg.init(); println(ENV["REPO_TOKEN"])'
after_success:
 - julia -e 'cd(Pkg.dir("JuliaFEM")); ENV["REPO_TOKEN"]=b04kTEUTiWDXPhP1VTgF6gu6mVlNOBNEB; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

