language: julia
os:
  - linux
julia:
#  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("JuliaFEM"); println(pwd()) ;Pkg.test("JuliaFEM"; coverage=true)'
after_success:
 - julia -e 'cd(Pkg.dir("JuliaFEM")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

